### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by taozhenlin** [JunXiaoRuo/unicom#3]
开启tiny后闪退
机型k40 miui13
日志：
BOARD=alioth
SOC_MANUFACTURER=QTI
IS_MIUI=true
CPU_ABI2=
IS_TIMINGTRACE=false
HOST=m1-xm-ota-bd329.bj.idc.xiaomi.com
versionName=2.0
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@2be68a3
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
IS_USERDEBUG=false
DISPLAY=SKQ1.211006.001 test-keys
HW_TIMEOUT_MULTIPLIER=1
SUPPORTED_ABIS=[Ljava.lang.String;@667a0
FINGERPRINT=Redmi/alioth/alioth:12/SKQ1.211006.001/V13.0.2.1.1.DEV:user/release-keys
PRODUCT=alioth
ID=SKQ1.211006.001
SOC_MODEL=SM8250
TYPE=user
SERIAL=unknown
IS_CONTAINER=false
IS_ENG=false
DEVICE=alioth
ODM_SKU=pro
TIME=1641918167000
IS_USER=true
MODEL=M2012K11AC
MANUFACTURER=Xiaomi
USER=builder
versionCode=8
BRAND=Redmi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@36f8fd2
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
SKU=unknown
TAGS=release-keys
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1487)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1373)
	at com.alibaba.fastjson.JSON.parse(JSON.java:182)
	at com.alibaba.fastjson.JSON.parse(JSON.java:192)
	at com.alibaba.fastjson.JSON.parse(JSON.java:148)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:253)
	at com.junruo.jiankong.MainActivity$7.onSuccess(MainActivity.java:372)
	at com.junruo.jiankong.MainActivity$7.onSuccess(MainActivity.java:368)
	at com.lzy.okhttputils.request.BaseRequest$4.run(BaseRequest.java:581)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by binbingb** [comment]
这是来自邮箱助手的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
